version: 2.1
orbs:
  codecov: codecov/codecov@1.1.3
jobs:
  code-arrival:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run:
          name: Code arrival
          command: |
            ls -al
            echo 'This is the code that has arrived'
  lib-testing:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - run:
          name: Install and run tests
          command: |
            yarn install && yarn test
      - codecov/upload:
          file: './coverage/clover.xml'
          token: fb8b10cf-f7e3-4432-8e61-177ae7e1c3e2

workflows:
 version: 2
 my-workflow:
   jobs:
     - code-arrival
     - lib-testing:
         requires:
           - code-arrival
